# official Python runtime as the base image
FROM openjdk:17

# Set the working directory within the container
WORKDIR /app

# current directory contents into the container at /app
COPY . /app

CMD ["java", "main.java"]