# official Python runtime as the base image
FROM python:3.8-slim

# Set the working directory within the container
WORKDIR /app

# current directory contents into the container at /app
COPY . /app


CMD ["python", "first.py"]
